import Head from 'next/head'
import Purchased from '../components/manage/purchased'
import Navbar from '../components/navbar/navbar'
import Welcome from '../components/welcome/welcome'
import styles from '../styles/Home.module.css'
import Highlight from './mainmenu/dashboard'
import Income from '../components/manage/income'
import IncomeCategoryChart from '../components/chart/income/category'
import SpendingCategoryChart from '../components/chart/spending/category'
import SpendingLineChart from '../components/chart/spending/spending'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.body}>
        <main className={styles.main}>
          <Navbar/>
          <Welcome/>
          <div className='row pb-5'>
            <div className='col-lg-3 col-md-6 col-sm-6'>
              <Highlight/>
            </div>
            <div className='col-lg-5 col-md-6 col-sm-6'>
              <SpendingLineChart/>
              <SpendingCategoryChart/>
            </div>
            <div className='col-lg-4 col-md-6 col-sm-12'>
              <Purchased/>
            </div>
            <div className='col-lg-3 col-md-6 col-sm-6'>
             
            </div>
            <div className='col-lg-5 col-md-6 col-sm-6'>
              <IncomeCategoryChart/>
            </div>
            <div className='col-lg-4 col-md-6 col-sm-12'>
              <Income/>
            </div>
          </div>
        </main>
      </div>
    </div>
  )
}
