import { useState, useEffect } from "react"
import Head from 'next/head'
import Income from '../../components/manage/income'
import IncomeCategoryChart from '../../components/chart/income/category'
import Purchased from '../../components/manage/purchased'
import SpendingCategoryChart from '../../components/chart/spending/category'
import SpendingLineChart from '../../components/chart/spending/spending'
import IncomeLineChart from '../../components/chart/income/weekly'
import styles from '../../styles/Home.module.css'
import Navbar from "../../components/navbar/navbar"
import Welcome from "../../components/welcome/welcome"

//Font awesome icon
import { library } from "@fortawesome/fontawesome-svg-core"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faChartLine, faChevronRight, faDollar, faEllipsisVertical, faMoneyBillTrendUp, faSackDollar } from "@fortawesome/free-solid-svg-icons"
import { } from "@fortawesome/free-regular-svg-icons"

export default function Highlight() {
    //Initial variable
    const [error, setError] = useState(null);
    const [isLoaded, setIsLoaded] = useState(false);
    const [items, setItems] = useState([]);
    var spend = 0;
    var spendDate;

    //Converter
    const data = Object.values(items);

    useEffect(() => {
        fetch("http://localhost:3000/api/total")
        .then(res => res.json())
          .then(
          (result) => {
            setIsLoaded(true);
            setItems(result.data);
          },
          (error) => {
            setIsLoaded(true);
            setError(error);
          }
        )
    },[])

    function countProfit(spend, income){
        var result = income - spend;
        if(result > 0){
            return (
                <h5 className='box-main-text' style={{color:"#00BB8C"}}>+ Rp. {result}</h5>
            );
        } else {
            return (
                <h5 className='box-main-text' style={{color:"#FF5691"}}>- Rp. {result}</h5>
            );
        }
    }

    function dateConvert(datetime){
        const result = new Date(datetime);
        const month = result.toLocaleString('default', { month: 'short' }); 
        const now = new Date(Date.now());
        const yesterday = new Date();
        yesterday.setDate(yesterday.getDate() - 1);
        
        if(result.toDateString() === now.toDateString()){
            return "Today";
        } else if(result.toDateString() === yesterday.toDateString()){
            return "Yesterday";
        } else {
            return ("0" + result.getDate()).slice(-2) + " " + month + " " + result.getFullYear();
        }
    }

    //Date convert for profit. Between spending and income
    function dateConvertProfit(spend_d, income_d){
        if(spend_d > income_d){
            return dateConvert(spend_d);
        } else {
            return dateConvert(income_d);
        }
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.body}>
                <main className={styles.main}>
                    <Navbar active={"dashboard"}/>
                    <Welcome/>
                    <div className='row pb-5'>
                        <div className='col-lg-3 col-md-6 col-sm-6'>
                            {
                                data.map((val, i, index) => {
                                    if(i == 0){
                                        return (
                                            <div className="box-highlight" key={i}>
                                                <h6><FontAwesomeIcon icon={faSackDollar} width="18px"/> &nbsp;&nbsp;Ballance</h6>
                                                <button className="btn btn-transparent box-setting" title="Setting"><FontAwesomeIcon icon={faEllipsisVertical} width="4.5px"/></button>
                                                <h5 className="box-main-text">Rp. {val.total}</h5>
                                                <h6 className="box-secondary-text">Last Updated: {dateConvert(val.lastdate)}</h6>
                                                <button className="btn btn-outline-more box-more" title="See more"><FontAwesomeIcon icon={faChevronRight} width="14px"/></button>
                                            </div>
                                        );
                                    }
                                    if(i == 1){
                                        spend = val.total;
                                        spendDate = val.lastdate;

                                        return(
                                            <div className="box-highlight" key={i}>
                                                <h6><FontAwesomeIcon icon={faDollar} width="13px"/> &nbsp;&nbsp;Spending</h6>
                                                <button className="btn btn-transparent box-setting" title="Setting"><FontAwesomeIcon icon={faEllipsisVertical} width="4.5px"/></button>
                                                <h5 className="box-main-text">Rp. {val.total}</h5>
                                                <h6 className="box-secondary-text">Last Updated: {dateConvert(val.lastdate)}</h6>
                                                <button className="btn btn-outline-more box-more" title="See more"><FontAwesomeIcon icon={faChevronRight} width="14px"/></button>
                                            </div>
                                        );
                                    } else if(i == 2){
                                        return(
                                            <div key={i}>
                                                <div className="box-highlight">
                                                    <h6><FontAwesomeIcon icon={faMoneyBillTrendUp} width="18px"/> &nbsp;&nbsp;Income</h6>
                                                    <button className="btn btn-transparent box-setting" title="Setting"><FontAwesomeIcon icon={faEllipsisVertical} width="4.5px"/></button>
                                                    <h5 className="box-main-text">Rp. {val.total}</h5>
                                                    <h6 className="box-secondary-text">Last Updated: {dateConvert(val.lastdate)}</h6>
                                                    <button className="btn btn-outline-more box-more" title="See more"><FontAwesomeIcon icon={faChevronRight} width="14px"/></button>
                                                </div>
                                                <div className="box-highlight">
                                                    <h6><FontAwesomeIcon icon={faChartLine} width="18px"/> &nbsp;&nbsp;Profit</h6>
                                                    <button className="btn btn-transparent box-setting" title="Setting"><FontAwesomeIcon icon={faEllipsisVertical} width="4.5px"/></button>
                                                    {countProfit(spend, val.total)}
                                                    <h6 className="box-secondary-text">Last Updated: {dateConvertProfit(spendDate, val.lastdate)}</h6>
                                                    <button className="btn btn-outline-more box-more" title="See more"><FontAwesomeIcon icon={faChevronRight} width="14px"/></button>
                                                </div>
                                            </div>
                                        );
                                    } 
                                })
                            }
                        </div>
                        <div className='col-lg-5 col-md-6 col-sm-6'>
                            <SpendingLineChart/>
                            <SpendingCategoryChart/>
                        </div>
                        <div className='col-lg-4 col-md-6 col-sm-12'>
                            <Purchased/>
                        </div>
                        <div className='col-lg-3 col-md-6 col-sm-6'>
                        
                        </div>
                        <div className='col-lg-5 col-md-6 col-sm-6'>
                            <IncomeLineChart/>
                            <IncomeCategoryChart/>
                        </div>
                        <div className='col-lg-4 col-md-6 col-sm-12'>
                            <Income/>
                        </div>
                    </div>
                </main>
            </div>
        </div>
    )
}
