import { useState, useEffect } from "react"
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from "../../components/navbar/navbar"
import Welcome from "../../components/welcome/welcome"

export default function History() {
    //Initial variable
    const [error, setError] = useState(null);
    const [isLoaded, setIsLoaded] = useState(false);
    const [items, setItems] = useState([]);

    //Converter
    const data = Object.values(items);

    useEffect(() => {
        fetch("http://localhost:3000/api/total")
        .then(res => res.json())
          .then(
          (result) => {
            setIsLoaded(true);
            setItems(result.data);
          },
          (error) => {
            setIsLoaded(true);
            setError(error);
          }
        )
    },[])

    return (
        <div className={styles.container}>
            <Head>
                <title>History</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.body}>
                <main className={styles.main}>
                    <Navbar active={"history"}/>
                    <Welcome/>
                    <div className='row pb-5'>
                    </div>
                </main>
            </div>
        </div>
    )
}
